---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-token
  namespace: gitea-runner
spec:
  encryptedData:
    token: AgB1qQZjoEH0FJN3qlJ5UcGtMluX2ayQzB3EkUj5wxAc84HOOMpcsfXPCKuxcSqwBV+fnRq8W9HNYxeKUaDG54oFKNq6yC92VMn09iBJDrwlHIKH51yHBhga700SvOW+3L1XKfh10palvMpZkVHOve5/oQT88qC+o22itB1/9CsC7Nvz/GqX2Y7mrJHDuv/JL494y/Ag5FM+5X021Tlma2US/Vo540Iu53p7pGkxh4qMYYxXVS9rdUR6ZWsVEkKhEcm+Vmg7MP1klPb6JIyM6nG8cAk34D7zs2mJO6XhCjLXJSGKLwGA+t8qLRtuETr/vgq1Xa0XL1o7DVupskwQHUiIiZ5AbrOoBL3tRi1n4FzXrNWTWJOcez/BRSvhqfBuCaRdjV66XKKIJTkIDdcZPbpeXDc+sOjzENe2vIFlrwZ5O2024OBsrEUr+Wj7KdfPHl0CPa+2acEwjkXXjH9dgjU4h/4Lv+xWFpZigOLTnyWdS2tHL+nQ59Ecsqqm8pwfws0Stk3L933GpVhaP/UukN//w+TRkQ1Irj139jqnHJTJ6lWFx9oFYadxQHbQbEqCCbI9nfgRa4WKIZNqADxcxvp9S0z3UJjYLzFiTOV3+lsV+tc7G6dOjFFKv7xI3G3e6SzwJDqvMJxpf6RpysRpUq5tWWFTAvc2HO39DTkNYR6eFLPsEkTwfoAm3+lJS5CvepoCJ7RlnrFYnTUSK6FuVKxOHBOayMftV0Ksdqokp/yDfwlavMqfl41e
  template:
    metadata:
      name: gitea-runner-token
      namespace: gitea-runner
