---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-token
  namespace: gitea-runner
spec:
  encryptedData:
    token: AgAlvvKLV5XvvQ2qUu8R5ln0WcsA9r/QO2Dcu+QY92BlKeOpBJAP8OT0vo9YZq6s/TxPmbbhdBtkrEtYqAMBynaUTad1ZWlYJ5+6skGiwNU2F30Vz1lyMcm8vbws8GpTRk5A3P4leiLwT+ozgipFrNVf4FGSkfYx8T5+4CiO++Bg9tJoVER4mpHfDPQfK92/Mqw9rUkk6g+3fsMhR0SiN+vI+HUJBW/WuBaVOG30RBB2PBoPKJ5S8a/spOp12JsnAi2YdcQ96toGXck4+KLveXymjbrQkfnwo7mvfwGj4LioGatTmYWMP/FKVPe9jFPmxnYVE1tumTl/+REE2I7gTRoaCuAXchG+i/KNT++qP0S0kcGvSMdPzB6ZGaE4kMzDG4CvNcwQ9zG9eei0JOGGPtIMaq3rZ735iYUlLcWkhlBNu/on8c5R4Szq9JxojhaW4EldWjkfT1tN8BeIKMt0OrBPQqsFy4y08vEbpTqeqHDoi0PaXH7cX7uWEXvtUAKmLlrdv3nihzv0uZIhYas1TNZVwyfjnPZ4lUsc1CHhIyvr7C/XJFzQT/wOFH0xreu15RjWWdNkIhmzfdupwJobF5XK/BRk+3Q6frNPLrDAkP4Q2jRvHihdHXZnj4PCAS3IswFFBWBYV2rxD1DEMAfva3h0CyrnM3zzttzzKgOgeaUt++VWTi2eLN4T4Sd263HP97h5EJDu0nGHySQqhSQQz030OBijQ/ZqWVWLd2QWUJqdDpcfV97yIBqg
  template:
    metadata:
      name: gitea-runner-token
      namespace: gitea-runner
