---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-token
  namespace: gitea-runner
spec:
  encryptedData:
    token: AgAwqxr66987riqfSEoJ7CRe587cJVraYaynjHN5y+Yi6OMhvlpoQNj3SUhxRQNc+mnS3T1KxFXMGm9phkhHXoUuGlhtcPbJC3CUP0B6kkGF4NrsJhpskX3QPePo2s48SV7PWq0uyrj2n67tHGxnvBmDdcd50RAu9mzxiXVuaFyms5NFOOLHKbff8Zbx6nP7/4xzozoDOND8CgRrQ+58n0keDu9UJersQ5DG2agHNuB2DffvUZLqY8jjKvBlxBGa+cVvT51mwN5ETYoCCnYiGPHw0HR6G5Po0DRXi2vfbHRjzbD70ZCra2ssvO0HZa8chS5OP9vLOqDHYDJB4K8g3KhAfFswON/5DJR3THE7yTnWYMBtkWem7ZvSg3kGsaz6QOlc0Y5CrtQ2JVQH52Id7OAIHlMA4N5QZh+k5roIFzENEe8zEI17BKKdCYoOjuU48rlEF6HVIVsZqvltwaK1MOkVXgen6BQyYlK6FmHxW2gHqtCcPeqrqGGPrFQqz4c/nxzSUz5Qy9WPG5lRQLbqBv//Omu7cHxNmvELKfQ7VxbrKXv/aZc7lO/7/qje31jFUj/zdxH5XAX98b0VgZnhmuoO/BNgGsl8zhiJqUajsOXiZ1cMIXqufYKcfPd9DQo6jAguluShdP7mWMaOz75dlCdEBTkCzweAbrpABVgUybFvcTud1r0ofygxlbJjGLMrlAlzmPEJxKowM5qITnXixAFRLVzuR96TaZn1ApoSTI7WpI0zRPwspFsy
  template:
    metadata:
      name: gitea-runner-token
      namespace: gitea-runner
