---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-runner-token
  namespace: gitea-runner
spec:
  encryptedData:
    token: AgCXFCyZq53vJKqtvpJI6bcpQJefBur8msZb1WZ9fYCN2TuRDx9Y9dHUYyCU62R+OP9eKqA6MoJCgrNi8196blmMVutHCseyHKPzF2wh98/G/szwITc4RlhnCjTPhiuNtPy1p1T8nOpfWNEIcROAT/zYHnZjBpylc1rKU2jcpK9A630qrXqaRGzB56BkysiAxyAnPfc7eKMMrEK9WPeSGX0JhFtFh9jeAbcn5M2EIRq2rLNMQcEsEmWTwKXHT65MhQk8iPTj568FJZPNam1tr7jN//oC64HAd8FrOQ3pz+bSmHRetwYFMdPPCNdGGBxdL+YqSVHNtOvD2QgMaugtiKt3K+I+vkOifdjOe7kiRuO67bkfMSu438YhKGhEFD8veDPPrhAecho1/i74YG+HnE8QJyH36uF5Hg59Qav7V2tHEsVgAuh0Idt5+/Y/6Bromrgti+/xMk9Hn5uQopwENYIZBC0PIo+z4It/0hIG8WB0PndBrkeTEiegWOYNUjUZK6OHjZVS3ZT1ip/ut03VFeTQL78N/kx9t4kG4gaa8jyXrBO98WnJdxZYaPHEu4SqBaLm2b0pdVQNZA7QPKACGE6rVlUa20PhYzebNtYKXQw6V1VuBIdoDmEq3X7HGaInToBrPi/EHODqZdtplVHUheCYXNwi++9Kd9MuprcqrfRO8hOGKTXi/jjgjqTmWHRDlD6ydV6a+VDePgjFhHYOYgS5G4aTVCYzxw7rsjYF9iJS7KtTrHz/4jvo
  template:
    metadata:
      name: gitea-runner-token
      namespace: gitea-runner
