apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openstack-clouds
  namespace: gitea-runner
spec:
  encryptedData:
    clouds.yaml: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: openstack-clouds
      namespace: gitea-runner
