---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openstack-clouds
  namespace: gitea-runner
spec:
  encryptedData:
    clouds.yaml: AgDJfo+9C6a8WyXxKfAaZEPyslm2kGODhcJal7I4MZYy/AUgSjP2vnPEiEYtzzD0uNMcT7aCiEevqNUZ1STULZLuiNUCe0NQYSXcze1P/RDLzbPtQ079HpZL8dhKokzCSnf7RLOz99A/SbDnvmpBE0ym5m/UhjqBTJQOvRVgiw9RcnzwumnkLUT2u48n4syiY+z9Xs38Qgxz1/5XJI+qdQKJhD8YRaVHccsP/D0bxoUgVurYNSi2j/hWNFTqx3bNOx1oLSeLic9YBHgy+KShqA+DV7r7alGls38AKOPV+562aDOhd2tHQVrc+7lLTruqPCAngWoDtS9dCo/lzWJzYsCpKjSgcVK6gvPj5RPduzd1MUmOAr6DCquIy+RDjof7OQmGEvlV9twqEDeyrwtUh0fSUUR++6y3sr//P4/Q0l50koqJx/+RUkeQKiRL17GMTcgfOd5ky0Pa4PaSFY1RYy/QzYUtTsM+uS61dm/6Pi6tPSrVmj0hF1T9v4WCnezjRYX6L7iVTdXs0uaPsiFHFnu9XuUP8Ds8d+Y2nfwfpJAxhIVRQtXf/qSsy+svskyXkIs2VYisTm1V0CDMGdOVXP1pS50jqQlu4dK4IQ6PsN+Qfd6KuKlxTPHXyt9fZBiqIeEeejjidzRX9z3s2J8DiVCrlw6T9GXi9opQSMw/OasVW6DbAdtJyfbgFL1rI0H6VfNq7LJc1JABSuAgJoYUPdxZglK6NW00oAyPnDyUCM3c9XAUdysu2n8LniCdxIw1mamS80UNNgDEH2tr6Fm1KWsaUpROzNUAMananxJvh+Ta1Y7AiqgG4LRP/YoY+Ld66Agg26OZPfed3cISvGt/cpxQusgnAPa5qOcHDHEWXVngsX9pyoWCGyUvjtS5MoX7gstG8OT6DRYCktSX+huGtnnbi8rN90MFLDZGTZ58mStF5kkV244hOXn8DahU0YkFcRZtNZ1bgn6NnGOpmTOP8YHullJ9OQdqQ4YmQR1lKMbGa7tkGDZUfwYw3vmqNANIze11wpxSmOitAMVU2w/EjR0t52ZRO0th38n4elGf36Ol2FMaKXXEnwq1ESJWmcYZ7Ow=
  template:
    metadata:
      name: openstack-clouds
      namespace: gitea-runner
