apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-runner
  namespace: gitea-runner
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-runner-config
  namespace: gitea-runner
data:
  config.yaml: |
    log:
      level: info
    runner:
      name: kind-runner
      capacity: 2
      file: /data/.runner
      labels:
        - "docker:docker://registry.demo.local/terraform-runner:0.1"
        - "terraform:docker://registry.demo.local/terraform-runner:0.1"
        - "localstack:docker://registry.demo.local/terraform-runner:0.1"
    container:
      network: host
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-runner
  namespace: gitea-runner
  labels:
    app: gitea-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-runner
  template:
    metadata:
      labels:
        app: gitea-runner
    spec:
      serviceAccountName: gitea-runner
      containers:
        - name: docker-dind
          image: docker:27-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run
        - name: act-runner
          image: gitea/act_runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: GITEA_INSTANCE_URL
              value: http://gitea.gitea.svc.cluster.local:3000
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitea-runner-token
                  key: token
            - name: CONFIG_FILE
              value: /config/config.yaml
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
            - name: OS_CLIENT_CONFIG_FILE
              value: /etc/openstack/clouds.yaml
            - name: OS_CLOUD
              value: devstack
          volumeMounts:
            - name: config
              mountPath: /config
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: openstack-clouds
              mountPath: /etc/openstack/clouds.yaml
              subPath: clouds.yaml
            - name: runner-data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: gitea-runner-config
        - name: docker-sock
          emptyDir: {}
        - name: openstack-clouds
          secret:
            secretName: openstack-clouds
        - name: runner-data
          emptyDir: {}
