apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../gitea-runner/manifests/runner.yaml
  - ../../gitea-runner/manifests/openstack-clouds-sealedsecret.yaml
  - ../../gitea-runner/manifests/gitea-runner-token-sealedsecret.yaml
