apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/runner.yaml
  - manifests/openstack-clouds-sealedsecret.yaml
  - manifests/gitea-runner-token-sealedsecret.yaml
