apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../network-lab/frr/namespace.yaml
  - ../../network-lab/frr/multus-net.yaml
  - ../../network-lab/frr/frr1.yaml
  - ../../network-lab/frr/frr2.yaml
