apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-ingress.yaml
  - argocd-cm.yaml
  - argocd-cmd-params-cm.yaml
  - argocd-allow-kubelet-probes.yaml
  - argocd-network-policies.yaml
  - secrets/argocd-admin-sealedsecret.yaml
